### ISSUE TITLE
Net beans 8.2 with Tab

### ISSUE THREAD

**Issue by denzel94** [emmetio/netbeans#28] opened 2016-10-20 11:48 UTC
Tab not working(

**Comment by junichi11** [comment] 2016-10-21 03:32
Missing information. Could you provide your exact information? e.g. version number of the plugin, your steps, e.t.c.

Just one. Did you check an option (Expand abbreviations with the TAB key)? : `Tools > Options > Miscellaneous > Emmet` 

Thanks.

**Comment by Ceyar** [comment] 2016-11-15 10:04
Hello,
does not work on Netbeans IDE 8.2.

After installing the new version "org-lorenzos-emmet-1.1.2.nbm". If I search for the shorcut Expand abreviations, it is TAB, but if make try, it doesn't work.

I'm on macOS Sierra v.10.12.1

thank's in advance

**Comment by Chris2011** [comment] 2016-11-15 10:07
Please read https://github.com/emmetio/netbeans/issues/28#issuecomment-255285657 and verify you enabled the option.

**Comment by Ceyar** [comment] 2016-11-15 10:14
Ho yes sorry,

it's work but something is special, but after expanding the tag you have to tap "Return" for using the TAB function, is that normal?

Thanks for your reactivity

**Comment by Chris2011** [comment] 2016-11-15 10:24
Yes it is working as designed.
The cursor is set into the <div>|</div>, what is expected and not wrong. The problem is, that it is expected to type text or smth like that. You can see it if you do a "div->tab" and type smth. The text will be highlighted and after that you can hit enter to break out of the emmet stuff. But yes, if you have a simple, empty div, cursor should be there but not waiting for return.
Return should make a new line as expected. This should be fixed.

It is the same as for if -> tab and you see if(foo) and foo will be seleceted to be changed. But this doesn't make sense in the HTML context.

Please make a new ticket for this

**Comment by Ceyar** [comment] 2016-11-15 10:34
Ok, I see.

Thank you for your answer!

I'll make a new ticket s sonn as possible.

Thank you again for your explanation and the plugin.

Best regards
Dan

**Comment by Chris2011** [comment] 2017-03-20 14:59
@Ceyar did you create a new ticket? If yes, we can close this ticket.

**Closed** 2017-05-03 14:09 UTC
